### ISSUE TITLE
Spec for Bonus section

### ISSUE THREAD

**Issue by sandyvern** [learn-co-curriculum/pokemon-scraper#17]
Is it possible to have a spec for the bonus section so that we can test to see if we have done it right...maybe that recognizes added an alter sql file as well as the #alter_hp.

**Comment by pletcher** [comment]
Fixed, thanks! https://github.com/learn-co-curriculum/pokemon-scraper/commit/2520ef69d62222845425944d2c6e0c8c5d7058f2
