### ISSUE TITLE
Bonus

### ISSUE THREAD

**Issue by tpstar** [learn-co-curriculum/pokemon-scraper#18]
I passed three main tests, and wanted to skip the bonus tests. But the local test indicator is still red and indicates I failed the local test.  The bonus tests are really confusing, so I'd like to skip those unless there is a clear instruction regarding how I can solve the bonus tests.  I am not even sure the spec file is written right.

In the bonus spec test, there is a line;

expect(@db.execute("knows_default_hp").flatten.first).to eq(60)

But, "knows_default_hp" does not look like any kind of sql syntax.

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by aturkewi** [comment]
@mendelB or @jjseymour Should this be closed?

cc @AnnJohn

**Comment by jjseymour** [comment]
@aturkewi I have two PR's open that fix the bonus tests and provide and updated solution for it. If those look good and can be merged then we should be good to close this.

**Comment by aturkewi** [comment]
Thanks @jjseymour 
Sorry that took me forever to get to. I ran it up local on my computer and it works, so I merged it in :)
