### ISSUE TITLE
Improve handling/instructions/tests for Pokemon ID values

### ISSUE THREAD

**Issue by gj** [learn-co-curriculum/pokemon-scraper#21]
I think handling the Pokemon ID values in [this manner](https://github.com/learn-co-curriculum/orm-mapping-to-tables/blob/master/README.md#the-id-attribute) would make a lot more sense. Currently, it's a bit confusing as to whether the lab/tests want us to assign each Pokemon an ID that is passed in as an argument, one that is scraped from the provided sample webpage, or one that is incremented each time a new Pokemon is added to the database. In the context of learning ORM, I think the third option is best.

Thoughts @mendelB ?

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.

**Comment by mendelB** [comment]
@gj That's a great point. After seeing yet more confusion about this lab, I have determined to just refactor the whole thing so that it makes more sense, has us deal with instances, and just in general aligns with the context we're in.
Thanks for pointing this out!

**Comment by gj** [comment]
Sounds good @mendelB !

I think moving it after the Mapping Ruby Classes to Database Tables lesson would make a lot of sense. That one serves as a much better introduction.

**Comment by ddhogan** [comment]
I completely agree!  This lab belongs later in the section, and there needs to be a note about the keyword arguments.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#30 .  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
