### ISSUE TITLE
Spec breaks when working on bonuses

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/pokemon-scraper#26]
I think this spec breaks: https://github.com/learn-co-curriculum/pokemon-scraper/blob/master/spec/pokemon_spec.rb#L23-L28 when working on the bonus. 

The bonus has students create an HP column with a default val. When this happens, the spec fails.

Spec can either be modded to also look for 60 as the HP, _or_ just not this in the readme!

**Comment by lizbur10** [comment]
I had to modify the spec to get the tests to pass with the bonus code.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#30 .  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
