### ISSUE TITLE
lesson is too early?

### ISSUE THREAD

**Issue by williamhancharek** [learn-co-curriculum/pokemon-scraper#27]
I was very confused with this lesson, but was able to easily understand it once I skipped ahead a few chapters - maybe this should be moved to after Mapping database rows to objects

**Comment by lizbur10** [comment]
I agree. It was a real mess trying to do this lab where it currently appears in the section. I wound up getting on AAQ and I felt like an idiot because the tech had no idea why I was having so much trouble with things that (I found out later) were pretty basic.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#30 .  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
