### ISSUE TITLE
Pokemon lab should come later in section?

### ISSUE THREAD

**Issue by lwebber** [learn-co-curriculum/pokemon-scraper#28]
It seems like the Pokemon lab needs to come later on in this section, after the lessons on mapping databases to objects. Right now it's positioned 2nd in the section, right after "Why an ORM is useful", but that lesson doesn't explain anything. It just says "you'll work more with these methods later."

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#30 .  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
