### ISSUE TITLE
Cannot do Bonus Tests because file is missing

### ISSUE THREAD

**Issue by YogiBogie** [learn-co-curriculum/pokemon-scraper#29]
When I change the 'xit' to 'it' in the Spec file for the 3 bonus tests I get an error saying that alter_table_migration.sql file is missing.  Without that file the tests won't run, is there someway to get that file or the contents of it back?  See screenshot for error message I am getting:

![image](https://user-images.githubusercontent.com/18690880/33050294-24915768-ce32-11e7-8501-54994b095116.png)

**Comment by lizbur10** [comment]
+1 for this issue. The file is in the Solution branch, so I wound up getting the code from there and creating the file myself in my fork. However, when I did that it broke the spec. I wound up adding hp to the table directly (in schema_migration.sql), changing line 27 of pokemon_spec.rb to match, and removing line 46, which calls the code to add hp to the table.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#30.  We will add this to our internal work queue and
notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
