### ISSUE TITLE
Test one asks for three yet expects four

### ISSUE THREAD

**Issue by BenitolSantos** [learn-co-curriculum/pokemon-scraper#31]
Pokemon
  .initialize
    is initialized with keyword arguments of name, type and db (FAILED - 1)
Failures:
  1) Pokemon .initialize is initialized with keyword arguments of name, type and db
     Failure/Error:
       def initialize(name:,type:,db:)
         @name = name
         @type = type
         @db = db
       end
     ArgumentError:
       unknown keyword: id
     # ./lib/pokemon.rb:4:in `initialize'
     # ./spec/pokemon_spec.rb:11:in `new'
     # ./spec/pokemon_spec.rb:11:in `block (2 levels) in <top (required)>'
     # ./spec/pokemon_spec.rb:15:in `block (3 levels) in <top (required)>'

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process
but thank you for helping us ensure that those who follow in your path will not
encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this
issue. 💙
