### ISSUE TITLE
Need for Improvement on Instructions

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/pokemon-scraper#32]
Hey there--
This lab is currently near impossible to complete without looking at the solution. I understand being vague to get students in the mindset of figuring out solutions on their own, but this is the first lab in the module. Information regarding sanitization needs to have it's own lesson, and I had to speak with two coaches before getting a link (not included in the lab instructions--https://stackoverflow.com/questions/675010/what-is-the-question-marks-significance-in-mysql-at-where-column) to explain why the question marks were being used in the SQL statement. 

Additionally, the instructions for the Bonus lab does not indicate that it is necessary to make a new database file--that's completely unexpected when previously in the instructions it said the only responsibility of the student was in the Pokemon class. It took me four "Ask a Questions" to complete the lab (while also looking at the solution on GitHub) and the first two times, the technical coach was completely uneducated and unable to provide any helpful links to explain the material covered in this lab.

**Comment by sgharms** [comment]
@helloamandamurphy This is useful. We will address this.

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#30. We are going to rewrite this section in early 2019. Thank you for your
feedback!

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
