### ISSUE TITLE
File Missing

### ISSUE THREAD

**Issue by tzip25** [learn-co-curriculum/pokemon-scraper#33]
alter_table_migration.sql missing

**Comment by kylecoberly** [comment]
Yeah, I wasn't clear if you were supposed to make this. Here's the schema change:

```
# db/alter_table_migration.sql
ALTER TABLE pokemon
ADD hp INTEGER;
```

Also, since that alteration only runs in the bonus problems, it makes the earlier insert statements and stuff a little wonky.

**Comment by maxwellbenton** [comment]
Hi @tzip25 and @kylecoberly,

Thank you for spotting this and providing feedback. We've added `alter_table_migration.sql` to master and believe this issue has been resolved. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
