### ISSUE TITLE
Sanitize link

### ISSUE THREAD

**Issue by katreesedarcene** [learn-co-curriculum/pokemon-scraper#35]
This link does not explain what sanitize is at all. I think it should be a better site or a well thought out video because of the importance of the info.

**Comment by maxwellbenton** [comment]
Hi @katreesedarcene,

Thank you for opening this issue. We've updated this lesson and incorporated changes based on your feedback. We've updated the section on sanitizing, replaced the link and shifted the focus towards the actually preferred method to use, parameterized queries.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
