### ISSUE TITLE
hp

### ISSUE THREAD

**Issue by katreesedarcene** [learn-co-curriculum/pokemon-scraper#36]
Also for people who don't play video games hp should be explained. When you google hp you are bombarded with hewlitt packard.

**Comment by maxwellbenton** [comment]
Hi @katreesedarcene,

Thank you for this feedback. We've actually gone ahead and removed the section that referenced `hp` as part of a general clean up of this section of material, but will definitely be more mindful of this sort of thing in the future.

Thank you for contributing to a Learn lesson.
