### ISSUE TITLE
Spec file is missing - cannot run tests.

### ISSUE THREAD

**Issue by m-gamao** [learn-co-curriculum/pokemon-scraper#37]
There is no spec file here.  Cannot run tests because no tests exist for this IDE.

**Comment by maxwellbenton** [comment]
Hi @guerilla17,

I took a look at this lab, but I am unable to replicate the issue you experienced. However, this lab did have pending tests that have been a source of confusion for students. We've removed these tests to help make the objectives of this lab clearer. If you are still experiencing an issue where you are not seeing a spec file on this lab, please reopen this ticket.
