### ISSUE TITLE
Potential handraise question to address

### ISSUE THREAD

**Issue by AnnJohn** [learn-co-curriculum/pokemon-scraper#4]
This was a handraise question that's worth looking at:

"There are a lot of steps in this lab without any feedback between accurately scraping the data and seeing if the correct results are in the database. I keep getting nil and an empty array. Can someone let me know if I either failed at: creating a new database, preparing that new database, entering data into that database, or some other problem altogether."

**Comment by SophieDeBenedetto** [comment]
we will write the scraper, students responsible for database-related code. also gen. better instructions, more step-by-step. for example: what is the "save" method, why do we need it, example of writing a method to connect your Ruby code to your database.

**Comment by SophieDeBenedetto** [comment]
@StevenNunez, @JeffKatzy, @blake41 what's your opinion on this as far as immersive? Do you like having the scraping part in there? We can make two versions if you'd prefer.

cc: @jmburges

**Comment by ipc103** [comment]
@deniznida and I agree - this lab has too many different learning objectives right now. Agree with giving them the scraper and just having this be setting up the database and methods.
