### ISSUE TITLE
Initialize test

### ISSUE THREAD

**Issue by coltonstaab1** [learn-co-curriculum/pokemon-scraper#8]
The initialize test reads :
"Pokemon
  .initialize
    is initialized with a name, type and db"

But it also requires that you enter an ID number for it to pass. I think the test description should be changed to reflect the fact that the Pokemon class needs to be initialized with an ID as well

**Comment by AnnJohn** [comment]
Hi @coltonstaab1 thanks for raising this issue. We'll look into this as soon as we can.

**Comment by mjhough** [comment]
This issue still hasn't been resolved. The description incorrectly does not reference the need for an id.
